### ISSUE TITLE
Flexbox does not work for HorizontalLayout because of leading ":before"

### ISSUE THREAD

**Issue by mpetzold** [vaadin/vaadin-ordered-layout#72] opened 2019-07-04 10:15 UTC
Flexbox - more specifically JustifyContentMode - does not work for HorizontalLayout because there is a leading "::before" element that is also used for space calculation.
```
public class Navigation extends HorizontalLayout {
	
	public Navigation() {
		this.setJustifyContentMode(JustifyContentMode.BETWEEN);
		this.setWidthFull();
		
		this.add(new Button("A"));
		this.add(new Button("B"));
	}
}
```
Result:
```
<vaadin-horizontal-layout [...] justify-content: space-between;>
	::before
	<vaadin-button tabindex="0" role="button" >A</vaadin-button>
	<vaadin-button tabindex="1" role="button" >B</vaadin-button>
</vaadin-horizontal-layout>
```
Should be:
```
<vaadin-horizontal-layout [...] justify-content: space-between;>
	<vaadin-button tabindex="0" role="button" >A</vaadin-button>
	<vaadin-button tabindex="1" role="button" >B</vaadin-button>
</vaadin-horizontal-layout>
```

**Comment by heruan** [comment] 2019-07-04 10:22
See also: https://github.com/vaadin/vaadin-ordered-layout/issues/66

**Comment by web-padawan** [comment] 2020-02-13 18:15
Closing as duplicate of #66.

**Closed by web-padawan** 2020-02-13 18:15 UTC
